// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WMS.Practice.Infrastructure;

#nullable disable

namespace WMS.Practice.APIs.Migrations
{
    [DbContext(typeof(WMSDbContext))]
    [Migration("20260325155651_CreateInitialDatabase")]
    partial class CreateInitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.InventoryIssue", b =>
                {
                    b.Property<string>("InventoryIssueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssueStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InventoryIssueId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryIssues", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.InventoryIssueEntry", b =>
                {
                    b.Property<string>("InventoryIssueEntryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("InventoryIssueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IssueLotId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("RequestedQuantity")
                        .HasColumnType("float");

                    b.HasKey("InventoryIssueEntryId");

                    b.HasIndex("InventoryIssueId");

                    b.ToTable("InventoryIssueEntries", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.IssueLot", b =>
                {
                    b.Property<string>("IssueLotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("InventoryIssueEntryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LotStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialLotId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("RequestedQuantity")
                        .HasColumnType("float");

                    b.HasKey("IssueLotId");

                    b.HasIndex("InventoryIssueEntryId")
                        .IsUnique();

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialLotId");

                    b.ToTable("IssueLots", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.IssueSubLot", b =>
                {
                    b.Property<string>("IssueSubLotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("IssueLotId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialSubLotId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("RequestedQuantity")
                        .HasColumnType("float");

                    b.HasKey("IssueSubLotId");

                    b.HasIndex("IssueLotId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MaterialSubLotId");

                    b.ToTable("IssueSubLots", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryLogAggregate.InventoryLog", b =>
                {
                    b.Property<string>("InventoryLogId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("AfterQuantity")
                        .HasColumnType("float");

                    b.Property<double>("ChangedQuantity")
                        .HasColumnType("float");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PreviousQuantity")
                        .HasColumnType("float");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InventoryLogId");

                    b.HasIndex("LotNumber");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryLogs", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.InventoryReceipt", b =>
                {
                    b.Property<string>("InventoryReceiptId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InventoryReceiptId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryReceipts", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.InventoryReceiptEntry", b =>
                {
                    b.Property<string>("InventoryReceiptEntryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("ImportedQuantity")
                        .HasColumnType("float");

                    b.Property<string>("InventoryReceiptId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InventoryReceiptEntryId");

                    b.HasIndex("InventoryReceiptId");

                    b.ToTable("InventoryReceiptEntries", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.ReceiptLot", b =>
                {
                    b.Property<string>("ReceiptLotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("ImportedQuantity")
                        .HasColumnType("float");

                    b.Property<string>("InventoryReceiptEntryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LotStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReceiptLotId");

                    b.HasIndex("InventoryReceiptEntryId")
                        .IsUnique();

                    b.HasIndex("MaterialId");

                    b.ToTable("ReceiptLots", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.ReceiptSubLot", b =>
                {
                    b.Property<string>("ReceiptSubLotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("ImportedQuantity")
                        .HasColumnType("float");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LotStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptLotId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReceiptSubLotId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReceiptLotId");

                    b.ToTable("ReceiptSubLots", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.Material", b =>
                {
                    b.Property<string>("MaterialId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MaterialClassId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaterialId");

                    b.HasIndex("MaterialClassId");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialClass", b =>
                {
                    b.Property<string>("MaterialClassId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MaterialClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialClassId");

                    b.ToTable("MaterialClasses", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialClassProperty", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MaterialClassId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PropertyId");

                    b.HasIndex("MaterialClassId");

                    b.ToTable("MaterialClassProperties", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialLot", b =>
                {
                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("ExistingQuantity")
                        .HasColumnType("float");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LotStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LotNumber");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialLots", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialLotProperty", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MaterialLotId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("int");

                    b.HasKey("PropertyId");

                    b.HasIndex("MaterialLotId");

                    b.ToTable("MaterialLotProperties", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialProperty", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PropertyId");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialProperties", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialSubLot", b =>
                {
                    b.Property<string>("MaterialSubLotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("ExistingQuantity")
                        .HasColumnType("float");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubLotStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialSubLotId");

                    b.HasIndex("LocationId");

                    b.HasIndex("LotNumber");

                    b.ToTable("MaterialSubLots", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeClassId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeClassId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.EmployeeClass", b =>
                {
                    b.Property<string>("EmployeeClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("EmployeeClassId");

                    b.ToTable("EmployeeClasses", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.EmployeeClassProperty", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeClassId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PropertyId");

                    b.HasIndex("EmployeeClassId");

                    b.ToTable("EmployeeClassProperties", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.EmployeeProperty", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("int");

                    b.HasKey("PropertyId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeProperties", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.Supplier", b =>
                {
                    b.Property<string>("SupplierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StockTakeAggregate.StockTake", b =>
                {
                    b.Property<string>("StockTakeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("AdjustedQuantity")
                        .HasColumnType("float");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PreviousQuantity")
                        .HasColumnType("float");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StockTakeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LotNumber");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockTakes", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StockTakeAggregate.StockTakeSubLot", b =>
                {
                    b.Property<string>("StockTakeSubLotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("AdjustedQuantity")
                        .HasColumnType("float");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialSubLotId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PreviousQuantity")
                        .HasColumnType("float");

                    b.Property<double>("QuantityDifference")
                        .HasColumnType("float");

                    b.Property<string>("StockTakeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StockTakeSubLotId");

                    b.HasIndex("StockTakeId");

                    b.ToTable("StockTakeSubLots", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StorageAggregate.Location", b =>
                {
                    b.Property<string>("LocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LocationId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StorageAggregate.LocationProperty", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PropertyId");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationProperties", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StorageAggregate.Warehouse", b =>
                {
                    b.Property<string>("WarehouseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StorageAggregate.WarehouseProperty", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PropertyId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseProperties", (string)null);
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.InventoryIssue", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.PersonAggregate.Customer", "Customer")
                        .WithMany("InventoryIssues")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.PersonAggregate.Employee", "Employee")
                        .WithMany("InventoryIssues")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.StorageAggregate.Warehouse", "Warehouse")
                        .WithMany("InventoryIssues")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.InventoryIssueEntry", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.InventoryIssue", "InventoryIssue")
                        .WithMany("Entries")
                        .HasForeignKey("InventoryIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryIssue");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.IssueLot", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.InventoryIssueEntry", "InventoryIssueEntry")
                        .WithOne("IssueLot")
                        .HasForeignKey("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.IssueLot", "InventoryIssueEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.Material", null)
                        .WithMany("IssueLots")
                        .HasForeignKey("MaterialId");

                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialLot", "MaterialLot")
                        .WithMany("IssueLots")
                        .HasForeignKey("MaterialLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryIssueEntry");

                    b.Navigation("MaterialLot");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.IssueSubLot", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.IssueLot", "IssueLot")
                        .WithMany("IssueSubLots")
                        .HasForeignKey("IssueLotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.StorageAggregate.Location", null)
                        .WithMany("IssueSubLots")
                        .HasForeignKey("LocationId");

                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialSubLot", "MaterialSubLot")
                        .WithMany("IssueSubLots")
                        .HasForeignKey("MaterialSubLotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("IssueLot");

                    b.Navigation("MaterialSubLot");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryLogAggregate.InventoryLog", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialLot", "MaterialLot")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("LotNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.StorageAggregate.Warehouse", "Warehouse")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialLot");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.InventoryReceipt", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.PersonAggregate.Employee", "Employee")
                        .WithMany("InventoryReceipts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.PersonAggregate.Supplier", "Supplier")
                        .WithMany("InventoryReceipts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.StorageAggregate.Warehouse", "Warehouse")
                        .WithMany("InventoryReceipts")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.InventoryReceiptEntry", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.InventoryReceipt", "InventoryReceipt")
                        .WithMany("Entries")
                        .HasForeignKey("InventoryReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryReceipt");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.ReceiptLot", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.InventoryReceiptEntry", "InventoryReceiptEntry")
                        .WithOne("ReceiptLot")
                        .HasForeignKey("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.ReceiptLot", "InventoryReceiptEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.Material", null)
                        .WithMany("ReceiptLots")
                        .HasForeignKey("MaterialId");

                    b.Navigation("InventoryReceiptEntry");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.ReceiptSubLot", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.StorageAggregate.Location", "Location")
                        .WithMany("ReceiptSubLots")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.ReceiptLot", "ReceiptLot")
                        .WithMany("ReceiptSubLots")
                        .HasForeignKey("ReceiptLotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("ReceiptLot");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.Material", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialClass", "MaterialClass")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialClass");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialClassProperty", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialClass", "MaterialClass")
                        .WithMany("Properties")
                        .HasForeignKey("MaterialClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialClass");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialLot", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.Material", "Material")
                        .WithMany("MaterialLots")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialLotProperty", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialLot", "MaterialLot")
                        .WithMany("Properties")
                        .HasForeignKey("MaterialLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialLot");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialProperty", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.Material", "Material")
                        .WithMany("Properties")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialSubLot", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.StorageAggregate.Location", "Location")
                        .WithMany("MaterialSubLots")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialLot", "MaterialLot")
                        .WithMany("SubLots")
                        .HasForeignKey("LotNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("MaterialLot");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.Employee", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.PersonAggregate.EmployeeClass", "EmployeeClass")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeClass");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.EmployeeClassProperty", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.PersonAggregate.EmployeeClass", "EmployeeClass")
                        .WithMany("Properties")
                        .HasForeignKey("EmployeeClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeClass");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.EmployeeProperty", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.PersonAggregate.Employee", "Employee")
                        .WithMany("Properties")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StockTakeAggregate.StockTake", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.PersonAggregate.Employee", "Employee")
                        .WithMany("StockTakes")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialLot", "MaterialLot")
                        .WithMany("StockTakes")
                        .HasForeignKey("LotNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS.Practice.Domain.AggregateModels.StorageAggregate.Warehouse", "Warehouse")
                        .WithMany("StockTakes")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("MaterialLot");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StockTakeAggregate.StockTakeSubLot", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.StockTakeAggregate.StockTake", "StockTake")
                        .WithMany("SubLots")
                        .HasForeignKey("StockTakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StockTake");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StorageAggregate.Location", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.StorageAggregate.Warehouse", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StorageAggregate.LocationProperty", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.StorageAggregate.Location", "Location")
                        .WithMany("Properties")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StorageAggregate.WarehouseProperty", b =>
                {
                    b.HasOne("WMS.Practice.Domain.AggregateModels.StorageAggregate.Warehouse", "Warehouse")
                        .WithMany("Properties")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.InventoryIssue", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.InventoryIssueEntry", b =>
                {
                    b.Navigation("IssueLot")
                        .IsRequired();
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryIssueAggregate.IssueLot", b =>
                {
                    b.Navigation("IssueSubLots");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.InventoryReceipt", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.InventoryReceiptEntry", b =>
                {
                    b.Navigation("ReceiptLot")
                        .IsRequired();
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.InventoryReceiptAggregate.ReceiptLot", b =>
                {
                    b.Navigation("ReceiptSubLots");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.Material", b =>
                {
                    b.Navigation("IssueLots");

                    b.Navigation("MaterialLots");

                    b.Navigation("Properties");

                    b.Navigation("ReceiptLots");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialClass", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialLot", b =>
                {
                    b.Navigation("InventoryLogs");

                    b.Navigation("IssueLots");

                    b.Navigation("Properties");

                    b.Navigation("StockTakes");

                    b.Navigation("SubLots");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.MaterialAggregate.MaterialSubLot", b =>
                {
                    b.Navigation("IssueSubLots");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.Customer", b =>
                {
                    b.Navigation("InventoryIssues");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.Employee", b =>
                {
                    b.Navigation("InventoryIssues");

                    b.Navigation("InventoryReceipts");

                    b.Navigation("Properties");

                    b.Navigation("StockTakes");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.EmployeeClass", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.PersonAggregate.Supplier", b =>
                {
                    b.Navigation("InventoryReceipts");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StockTakeAggregate.StockTake", b =>
                {
                    b.Navigation("SubLots");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StorageAggregate.Location", b =>
                {
                    b.Navigation("IssueSubLots");

                    b.Navigation("MaterialSubLots");

                    b.Navigation("Properties");

                    b.Navigation("ReceiptSubLots");
                });

            modelBuilder.Entity("WMS.Practice.Domain.AggregateModels.StorageAggregate.Warehouse", b =>
                {
                    b.Navigation("InventoryIssues");

                    b.Navigation("InventoryLogs");

                    b.Navigation("InventoryReceipts");

                    b.Navigation("Locations");

                    b.Navigation("Properties");

                    b.Navigation("StockTakes");
                });
#pragma warning restore 612, 618
        }
    }
}
